title: Sai Gokhale
description: A brief overview of my recent work and interests!
theme: just-the-docs

url: https://saigokhale.github.io/portfolio

aux_links:
  Template Repository: https://github.com/saigokhale/portfolio
