title: Sai Gokhale Portfolio
description: A brief overview of my interests snd recent work in the field!
theme: just-the-docs

url: https://saigokhale.github.io/

aux_links:
  Template Repository: https://github.com/saigokhale/saigokhale2002.github.io
