title: Sai Gokhale
description: A brief overview of my recent work and interests!
theme: just-the-docs

url: https://saigokhale.github.io/portfolio

just_the_docs:
  color_scheme: dark
  search_enabled: false
  stylesheets:
    - assets/css/custom.css

aux_links:
  Resume: https://drive.google.com/file/d/1Sm21QpEjcmuG8b7mihmO0Qo8CcSxy4yu/view